version: 2

updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: monthly
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    groups:
      dev-dependencies:
        patterns:
          - 'illuminate/*'
          - 'laravel/*'
          - 'orchestra/*'
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      timezone: "Asia/Jakarta"
    open-pull-requests-limit: 5
    versioning-strategy: increase-if-necessary
    groups:
      dev-dependencies:
        patterns:
          - '@commitlint/*'
          - 'husky'
          - 'lint-staged'
        update-types: [minor, patch]
