name: Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
    paths:
      - .github/workflows/test.yml
      - src/*
      - tests/*

# env:
#   COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
#   CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
#   CC_TEST_REPORTER_URL: https://codeclimate.com/downloads/test-reporter/test-reporter-0.7.0-linux-amd64

jobs:
  test:
    name: Test with PHP ${{ matrix.php }}
    runs-on: ubuntu-20.04
    env:
      GIT_COMMIT_SHA: ${{ github.sha }}
      GIT_BRANCH: ${{ github.ref }}

    strategy:
      matrix:
        php: ['8.1']

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2
        coverage: xdebug

    - name: Get Composer cache directory
      id: composer-cache
      run: |
        echo "GIT_BRANCH=$(echo ${GIT_BRANCH##*/} | tr / -)" >> $GITHUB_ENV
        echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache Composer dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run tests
      run: composer test
